language: javascript

addons:
  firefox: "29.0"
  
env:
  global:
    - DISPLAY=":99.0"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq language-pack-ja
  - sudo apt-get install -qq pulseaudio
  # for travis/travis-cookbooks #155
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - sleep 3 
  - "firefox -profile ./firefox_profile -no-remote"
  - sleep 3
  - "./run_test.sh"


after_script:
  - firefox --version
  - sh -e /etc/init.d/xvfb stop


