language: javascript

before_script:
   - sudo apt-get install -qq pulseaudio
   - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
   - "export DISPLAY=:99.0"
   - sh -e /etc/init.d/xvfb start
 
script:
  - ./run_test.sh
  
after_script:
  - firefox --version
  - sh -e /etc/init.d/xvfb stop
